"""
Django settings for primer_proyecto project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for primer_proyecto project.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# CONFIGURACIÓN GENERAL


SECRET_KEY = 'django-insecure-n2)-5)_7hcrv88=6q%3dqs45qi-%f#@*689!5dyq^p=#+au3=l'

DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'usuarios.Usuario'

SITE_NAME = "TeoBits: Fe. Info. Al Instante."



# EMAIL

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "jorchwork@gmail.com"
EMAIL_HOST_PASSWORD = "TU_PASSWORD"   # ← actualizar
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# APLICACIONES INSTALADAS


INSTALLED_APPS = [
    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps propias
    'apps.usuarios',
    'apps.posts',
]



# MIDDLEWARE


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'primer_proyecto.urls'



# TEMPLATES


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ⭐ Nuestro context processor para categorías
                'apps.posts.context_processors.categorias_nav',
            ],
        },
    },
]


WSGI_APPLICATION = 'primer_proyecto.wsgi.application'



# BASE DE DATOS


DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'primer_proyecto',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'sql_mode': 'STRICT_TRANS_TABLES',
        }
    }
}



# VALIDACIÓN DE PASSWORD

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]



# INTERNACIONALIZACIÓN

LANGUAGE_CODE = 'es-ar'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True



# ARCHIVOS ESTÁTICOS / MEDIA


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#agrego que cuando cierre sesion, rediriga a la página de inicio
LOGOUT_REDIRECT_URL = "index"